on:
  workflow_dispatch: {}
  pull_request: {}
permissions:
  contents: read
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    
    # Check the environment variables before the scan
    - name: Print environment variables before scan
      run: |
        echo "Environment variables before semgrep scan:"
        env

    # Run the semgrep ci scan
    - run: |
        semgrep ci --quiet

    # Check the environment variables after the scan
    - name: Print environment variables after scan
      run: |
        echo "Environment variables after semgrep scan:"
        env
